title:             Wang Siyao
email:             wangsiyao0713@gmail.com
description:       Master of Science in Computer Science, Brown University
author:            Wang Siyao
baseurl:           ""
url:               "http://wangsiyao.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   WangSiyao
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
